var GAME_LEVELS = [
  /*["xxxxxxxxxxx    xxxxxxxxxx   xxxxxxx   xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   "!!!!!!!!!!! v  !!!!!!!!!! v !!!!!!! v !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!",
   "xxxxxxxxxxx    xxxxxxxxxx   xxxxxxx   xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   "                                                                                ",
   "                                                                                ",
   "                                                                  o             ",
   " o                                                              xxxxx           ",
   "xx                                                                              ",
   "                                                 xxxxxxyyyyyxxxxxxxxxxxxxxxxxxxx",
   "      xxx                 o         o          xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   "                 o                             x!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!",
   "xxx                                          xxxxxxxxxxxxxxxxxxxxxx xxx xxxxxxxx",
   "                                                                   v   v        ",
   "      o                                                                         ",
   "     xxx            xxxx      xxxx     xxxx                                     ",
   "                 o  x  x      x  x     x  x       o                  o          ",
   "  @             xxxx   xyyyyyyx  xyyyyyx  x     xxxx             o   o   o      ",
   "xxxxxxxxxx      x      x      x  x     x  x     x  x                            ",
   "         xyyyyyyx      x      x  x     x  xxx   x  xxxx    xxxxxxxxxxxxxxxxxxxxx",
   "         x      x      x      x  x     x  x     x     x!!!!x                    ",
   "         x      x      x      x  x     x  x     x     x!!!!x                    ",
   "         x      x      x      x  x     x  x     x     x!!!!x                    ",
   "         x      x      x      x  x     x  x     x     x!!!!x                    ",
   "         x      x      x      x  x     x  x     x     x!!!!x                    "],*/
 /*"                                                                                                                  ",
   "                                                                                                                  ",
   "                                                                                                                  ",
   "                                                                                    xxxxx                         ",
   "        o                     o     o                                                  xx!!!!!!!!!!!!!!xxxxx      ",
   "  @                              o                                  o                   xxxxxxxxxxxxxxxx          ",
   "xxxxx   o   xxxx!!xx       xxxxxxxxxxxxxx                   xxxxxxx   xxxxxx                                      ",
   "    x       x   v          x!!!!!!!!!!!!x    o           xxx!!!!!!xyyyx!!!!!v                                     ",
   "    x   o   x              xxxxxxvxxxxxxx          xxxxxxxxxxxx vxxxxxxxxxx                                       ",
   "    x       x                                                                                                     ",
   "    x  o    x                                                                                                     ",
   "    x       x                                                                                                     ",
   "    x o     x                          xxyyyyyxx                                        xx                  xxx   ",
   "    x       x       xxx          o     x!!!!!!!x                                       x=       m             x   ",
   "    x       x         x       xxxxxxx  xxxvxxxxx                        o           xxxxxxyyyyxxxxxxyyyyxxxxxxx   ",
   "    x       x         x       x!!!!!x                          xxxxxyyyxxxxxxxxx       x!!!!!!!!!!!!!!!!!!!!!x    ",
   "    x    o  x  o    o x       xxxvxxx                                                    xxx|xxxxx|xxxxxxx|xx     ",
   "    x       xxxxxxxxxxx                                                                                           ",
   "    x                                                                                                             ",
   "    x                            o                           xxx                                 ooo              ",
   "    x                                         xxxyyyyyxxx                           o                             ",
   "    xxx                    j                 =x         x                                xxx         xxxxxxxx     ",
   "    x                 xxxxxxxxx    xxxxxxxxxxxx         x o       xxxxxxxxxxxxxx     |   x  x        x       x    ",
   "    x!!!!!!!xxxxxxx   x       x    x                    x         =            xxx!!!!!xxx   xxx     x        x   ",
   "    x!!!!!!!x     x   x       x    x                    xxxxx     x            x !!!!!!!!x     xyyyyyx         x  ",
   "    x!!!!!!!x     xyyyx       xyyyyx                         yyyyyx              !!!!!!!!      x     x         x  ",
   "    x!!!!!!!x                                                                                                     ",
   "    x!!!!!!!x                                                                                                     ",
   "    x!!!!!!!x                                                                                                     ",
   "    x!!!!!!!x                                                                                                     "],*/
  /*                                                                                                              ",
   " @                                                                                   o                        ",
   "xxxx                                                                    o           xxx                       ",
   "x   x                                                                  xxx         xxxxx                  o   ",
   "x   xx       o                                                 o                    xxx                 xxxxxx",
   "x    xx    xxxx          o              o             j       xxx                                        v!!!!",
   "x     xxooxxxxxx                                     xxx                                                 vxxxx",
   "x      xxxx    xx                       x                                                                v    ",
   "x       xvx     xxxxx                   x      xxx                          o              o                  ",
   "x               v  xxxxx    xxxxx       x                                                                     ",
   "x                    xxxyyyx!!!!!xxx    xxxx                                            xxxyyxxx              ",
   "x                      xxxxxxxvxxxxx    x   x                         xxxxxxyyyx                            o ",
   "x    |      |          x                x    x                                                       xxxxxxxxx",
   "x x!!!!!!!!!!!!!!!!!xxxx                x!!!!!=                o                                              ",
   "x   xxx!!!!!!!!!xxxx                    xxx!!!!x             o    o             o                             ",
   "x      xxxx|xxxx                      xxxxx!!!!!x=          o      o                         o            m   ",
   "x                               o    xx   x!!!!!xxx       xxxxxyyxxxx           o                        xxxx ",
   "x=                    o            x     x!!!!!x=                                          xxx                ",
   "x                                  x      xxxxx!xxx                        xxxxxxxx                           ",
   "x               o        xxyyyxxxxx       xxxxx!xxxxx   o                                                     ",
   "x                     xxxxxxxxxxxxx       xx   v     x              o                                         ",
   "x          o       xxxxxx                 xx          x                                                       ",
   "x              yyyyxx!!!!!!!!!!!!!!!!!!!!!xx           x           xxx                               o        ",
   "x=           xxxxxxx!!!!!!!!!!!!!!!!!!!!!!xx        |   xxxxx                                      xxxxxx     ",
   "xxxxxx     xxxxxxxxxxvxxxvxxxxvxxxxxxxvxxxxx                 x                    xxx                         ",
   "                                o         xx                 xx    xx                                         ",
   "                o        o              o xx                xxx                                               ",
   " o            xxxxx            xxx        xx!!!!!!!!!!!!!!!!=               o                                 ",
   "x           xx     xxxxxyyyxxxxxxxxxyyyxxxxx!!!!!!!!!!!!xxx              xxxxxx                               ",
   " xxx!!xx   x          xxxxxxxxxxxxxxxxxxxxx!!!!!xvx!!!!x                                                      ",
   "   xvxx                   xxxxxxxxxxxxxxxx!!!!!x   x!!x                                                       ",
   "  o                          x!!!!!!!!!!!!!xxxx     x|                       xxxxx      o                     ",
   "          o                  =!!!!!!!!!!!!!=                                                                  ",
   "xx                            xxxxxvxxvxxxx                                           xxxxx              xxx  ",
   "  xxxxxxxxxxx                                                                                            x x  ",
   "  x          xxx                    o                                  o      xxxxx                       ox  ",
   "  xxx       o  xx                                       o                                                  x  ",
   "  x           xxxxx                                            xxx    xxxx                    o          xxx  ",
   "  x  o    xxxxx                   xxxxxxx              xxx                xx                  o            x  ",
   "  xxxx                   o                    xxxx                                         xxxxxxx         x  ",
   "  x              o                                                                         x     x         x  ",
   "  x o           xxx     xxx    xxyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyx       xyyyyyyyyyxx      xyyyyyyyyyx  ",
   "  xxxxyyyxx                     xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx      xxxxxxxxxxxx     xxxxxxxxxxxxx  ",
   "  xxxxxxxxxxx!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!=                                   x  ",
   "  xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx!!!!!!xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx  ",
   "                                                                                                              ",
   "                                                                                                              "],*/
  ["                                                                                                              ",
   "  @                          xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx  ",
   " xxxxxxxxxxxxxxxxxxxxxxxxx o xxxxxxxx o xxxxx o o o o o oxxxxxxx o xxxxxxxxxx o xxxxxxxxxxxxxxxxxxxxxxxxxxxx  ",
   " xxxxxxxxxxxxxxxxxxxxxxxxxx o xxxxxx o xxxxx o xxxxxxxx o xxxxxx o xxxxxxxxxx o xxxxxxxxxxxxxxxxxxxxxxxxxxxx  ",
   " xxxxxxxxxxxxxxxxxxxxxxxxxxx o xxxx o xxxxx o xxxxxxxxxx o xxxxx o xxxxxxxxxx o xxxxxxxxxxxxxxxxxxxxxxxxxxxx  ",
   " xxxxxxxxxxxxxxxxxxxxxxxxxxxx o xx o xxxxxx o xxxxxxxxxx o xxxxx o xxxxxxxxxx o xxxxxxxxxxxxxxxxxxxxxxxxxxxx  ",
   " xxxxxxxxxxxxxxxxxxxxxxxxxxxxx o  o xxxxxxx o xxxxxxxxxx o xxxxx o xxxxxxxxxx o xxxxxxxxxxxxxxxxxxxxxxxxxxxx  ",
   " xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx oo xxxxxxxx o xxxxxxxxxx o xxxxx o xxxxxxxxxx o xxxxxxxxxxxxxxxxxxxxxxxxxxxx  ",
   " xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx oo xxxxxxxx o xxxxxxxxxx o xxxxxx o xxxxxxxx o xxxxxxxxxxxxxxxxxxxxxxxxxxxxx  ",
   " xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx oo xxxxxxxxx o xxxxxxxx o xxxxxxxx o xxxxxx o xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx  ",
   " xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx oo            o o o o o             o o o o xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx  ",
   " xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx                                               xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx  ",
   " xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx    xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx  ",
   " xxxxxxxxxxxxxxxxx o xxxxxxxxxxxxxxxx o     o o o o o o o o oxx o o  xxxxxx o xxxxx!!!xxxxxxxxxxxxxxxxxxxxxx  ",
   " xxxxxxxxxxxxxxxxxx o xxxxxxxxxxxxxx o              o        xx o   o xxxxx o xxxxx!!!xxxxxxxxxxxxxxxxxxxxxx  ",
   " xxxxxxxxxxxxxxxxxxx o xxxxxxxxxxxx o xxxxxxxxxxxxx o    xxxxxx o x  o xxxx o xxxxx!!!xxxxxxxxxxxxxxxxxxxxxx  ",
   " xxxxxxxxxxxxxxxxxxxx o xxxxooxxxx o xxxxxxxxxxxxxx o   xxxxxxx o xx  o xxx o xxxxx!!!xxxxxxxxxxxxxxxxxxxxxx  ",
   " xxxxxxxxxxxxxxxxxxxxx o x o o ox o xxxxxxxxxxxxxxx o    xxxxxx o xxx  o xx o xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx  ",
   " xxxxxxxxxxxxxxxxxxxxxx o o    o o xxxxxxxxxxxxxxxx o xxxxxxxxx o xxxx  o x o xxxxx!!!xxxxxxxxxxxxxxxxxxxxxx  ",
   " xxxxxxxxxxxxxxxxxxxxxxx o xxxx o xxxxxxxxxxo o o o o o o o o   o xxxxx   o o xxxxx!!!xxxxxxxxxxxxxxxxxxxxxx  ",
   " xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx                    xxxxxxxx      xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx  ",
   "  xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx ",
   "                                                                                                              "]
];

if (typeof module != "undefined" && module.exports)
  module.exports = GAME_LEVELS;
